[project]
name = "cli-t212-to-digrin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.18",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
]
